---
title: "The Rhythm of the Loop"
subtitle: "What GW's clothing exchange reveals about what people need (and when)"
format:
  html:
    page-layout: full
---

```{=html}
<iframe src="waffle-time/dist/index.html" width="100%" height="600" style="border:none;"></iframe>
```

## About

This visualization was created for [GW's first annual Data Visualization Competition](https://library.gwu.edu/george-washington-university-2026-data-visualization-competition) in support of International Love Data Week 2026. The competition is organized by GW LAI and Himmelfarb Health Sciences Library in partnership with the GW Office of Sustainability, the Open Source Program Office, and the Office of the Vice Provost for Research.

Participants were asked to create data visualizations based on a dataset from [The Loop Clothing Exchange](https://sustain.gwu.edu/loop-clothing-exchange), located on GW's Mount Vernon Campus. The Loop is a free clothing exchange that allows the GW community to donate and take clothing, promoting sustainability and reducing textile waste.

### Author

[John Paul Helveston](https://www.jhelvy.com), Associate Professor in the Department of Engineering Management and Systems Engineering at George Washington University.

### Source Code

The code for this project is available on GitHub: <https://github.com/jhelvy/gw-dataviz-2026>
